name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
#  push:
#    branches:
#      - main
#    paths:
#      - 'starter/backend/**'

env:
  PYTHON-VERSION: "3.10"
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev
      - name: Run lint
        run: |
          cd starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run tests 
        run: |
          cd starter/backend
          pipenv run test
        
  dev-notes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3    
      - name: Display Development Notes
        run: |
          echo "These are the Development notes"
          cat README.md

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run tests 
        run: |
          cd starter/backend
          pipenv run test        
      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build --tag backend:latest .