
name: Frontend Continuous Integration

on:
  workflow_dispatch:
 # pull_request:
   push:
     branches:
       - main
     paths:
       - 'starter/frontend/**'

env:
  NODE-VERSION: 18.14
  REACT_APP_MOVIE_API_URL: "http://localhost:5000"
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci          
      - name: Run lint
        run: |
          cd starter/frontend
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci
      - name: Run tests 
        run: |
          cd starter/frontend
          npm test
        
  dev-notes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3    
      - name: Display Development Notes
        run: |
          echo "These are the Development notes"
          cat README.md

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm          
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci
      - name: Run tests 
        run: |
          cd starter/frontend
          npm test --passWithNoTests         
      - name: Build Docker Images
        run: |
          cd starter/frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} --tag=frontend:latest .